#!/usr/bin/env python3
"""Evil Overlord Personal Assistant"""

import eviloverlord

VERSION = 'v0.2.0-1'

def main():
    """Main function for Evil Overlord"""
    # Generate the command line interface
    parser = eviloverlord.commandline.generate_commandline(VERSION)

    # Parse the arguments
    args = parser.parse_args()
    eviloverlord.log.debug(args)

    # Handle the command line
    eviloverlord.commandline.handle_commandline(parser, args)

if __name__ == '__main__':
    main()
