// Code generated by "stringer -type Callback"; DO NOT EDIT.

package cmds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildCommandTree-0]
	_ = x[ModuleInit-1]
	_ = x[Backup-2]
	_ = x[Restore-3]
	_ = x[maxCallbacks-4]
}

const _Callback_name = "BuildCommandTreeModuleInitBackupRestoremaxCallbacks"

var _Callback_index = [...]uint8{0, 16, 26, 32, 39, 51}

func (i Callback) String() string {
	if i < 0 || i >= Callback(len(_Callback_index)-1) {
		return "Callback(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Callback_name[_Callback_index[i]:_Callback_index[i+1]]
}
